[package]
name = "pi_hole_api"
version = "0.1.0"
authors = ["Connor Holloway <c.holloway314@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
reqwest = { version = "0.10.4", features = ["json"] }
tokio = { version = "0.2.20", features = ["rt-threaded", "macros"] }